import '@/styles/globals.css';

import { Header } from '@/components';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
